#!/usr/bin/env python3
"""Generate AI_MEMORY_PACK.md from source documents under docs/AI/.

Usage:
    python tools/generate_ai_memory.py          # validate + generate
    python tools/generate_ai_memory.py --check  # validate only, no file changes
"""

from __future__ import annotations

import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs" / "AI"
OUTPUT = DOCS / "AI_MEMORY_PACK.md"

MEMORY_VERSION = "v2.0"
PROJECT = "RuleForge"

SOURCE_FILES = [
    "PROJECT_BRIEF.md",
    "CURRENT_STATUS.md",
    "AI_HANDOFF.md",
    "ARCHITECTURE.md",
    "DEVELOPMENT_CONSTITUTION.md",
    "AI_WORKFLOW.md",
    "TEST_STRATEGY.md",
    "DECISION_LOG.md",
    "KNOWN_LIMITATIONS.md",
    "NEXT_MILESTONE.md",
    "CHANGELOG_AI.md",
    "REVIEW_GUIDELINES.md",
]

SECTION_TITLES = {
    "PROJECT_BRIEF.md": "Project Summary",
    "CURRENT_STATUS.md": "Current Status",
    "ARCHITECTURE.md": "Architecture Overview",
    "DEVELOPMENT_CONSTITUTION.md": "Engineering Constitution",
    "AI_WORKFLOW.md": "Workflow",
    "TEST_STRATEGY.md": "Testing Strategy",
    "DECISION_LOG.md": "Architecture Decisions",
    "KNOWN_LIMITATIONS.md": "Known Limitations",
    "NEXT_MILESTONE.md": "Current Planning",
    "CHANGELOG_AI.md": "Milestone History",
    "REVIEW_GUIDELINES.md": "Reviewer Guidance",
    "AI_HANDOFF.md": "Session Recovery",
}


def read_doc(name: str) -> str:
    path = DOCS / name
    if not path.is_file():
        return f"(missing: {name})"
    return path.read_text(encoding="utf-8").strip()


def extract_field(text: str, field: str) -> str:
    for line in text.splitlines():
        clean = line.strip().replace("**", "")
        if clean.startswith(field):
            return clean.split(":", 1)[-1].strip()
    return "?"


def extract_test_count(text: str) -> str:
    for line in text.splitlines():
        if "PASS" in line and ("tests" in line.lower() or "test" in line.lower()):
            return line.strip()
    return "?"


def summarize(text: str, max_lines: int = 15) -> str:
    lines = text.splitlines()
    content = [l for l in lines if not l.startswith("# ") and l.strip()]
    if len(content) <= max_lines:
        return "\n".join(content)
    return "\n".join(content[:max_lines]) + "\n  ..."


def validate() -> list[str]:
    errors: list[str] = []
    for name in SOURCE_FILES:
        path = DOCS / name
        if path.is_file():
            print(f"  {name:<30s} PASS")
        else:
            print(f"  {name:<30s} FAIL — missing")
            errors.append(f"{name}: missing")

    # Cross-doc consistency from README_AI.md
    readme_path = ROOT / "README_AI.md"
    if readme_path.is_file():
        readme = readme_path.read_text(encoding="utf-8")
        readme_version = extract_field(readme, "AI Memory Version")
        if readme_version == MEMORY_VERSION:
            print(f"  {'Memory Version':<30s} PASS ({MEMORY_VERSION})")
        else:
            print(f"  {'Memory Version':<30s} FAIL ({readme_version} != {MEMORY_VERSION})")
            errors.append(f"Version mismatch: {readme_version} != {MEMORY_VERSION}")
    else:
        print(f"  {'README_AI.md':<30s} FAIL — missing")
        errors.append("README_AI.md: missing")

    status = read_doc("CURRENT_STATUS.md")
    milestone = extract_field(status, "Version")
    print(f"  {'Milestone':<30s} {milestone}")

    tests = extract_test_count(status)
    print(f"  {'Tests':<30s} {tests}")

    return errors


def generate() -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    status = read_doc("CURRENT_STATUS.md")
    milestone = extract_field(status, "Version")
    freeze = "Enabled" if "Feature Freeze" in status else "Disabled"
    tests = extract_test_count(status)

    lines: list[str] = []
    lines.append("# AI Memory Pack")
    lines.append("")
    lines.append("| Field | Value |")
    lines.append("|---|---|")
    lines.append(f"| Version | {MEMORY_VERSION} |")
    lines.append("| Status | Generated File |")
    lines.append("| ⚠️ | Do NOT edit manually |")
    lines.append(f"| Generated At | {now} |")
    lines.append(f"| Generated By | tools/generate_ai_memory.py |")
    lines.append(f"| Project | {PROJECT} |")
    lines.append(f"| Current Milestone | {milestone} |")
    lines.append(f"| Feature Freeze | {freeze} |")
    lines.append(f"| Tests | {tests} |")
    lines.append("")
    lines.append("**Source Documents**: " + ", ".join(SOURCE_FILES))
    lines.append("")
    lines.append("---")
    lines.append("")

    # ToC
    lines.append("## Table of Contents")
    lines.append("")
    for i, name in enumerate(SOURCE_FILES):
        title = SECTION_TITLES.get(name, name)
        lines.append(f"{i+1}. [{title}](#{title.lower().replace(' ', '-')})")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Sections
    for name in SOURCE_FILES:
        title = SECTION_TITLES.get(name, name)
        text = read_doc(name)
        lines.append(f"## {title}")
        lines.append(f"> Source: [`{name}`]({name})")
        lines.append("")
        lines.append(summarize(text))
        lines.append("")
        lines.append("---")
        lines.append("")

    return "\n".join(lines)


def main() -> None:
    if "--check" in sys.argv:
        print("AI Memory Validation")
        print("=" * 50)
        errors = validate()
        print("=" * 50)
        if errors:
            print(f"FAIL ({len(errors)} errors)", file=sys.stderr)
            sys.exit(1)
        print("Overall: PASS")
        return

    errors = validate()
    if errors:
        print("\nValidation FAILED. Aborting.", file=sys.stderr)
        sys.exit(1)

    content = generate()
    OUTPUT.write_text(content, encoding="utf-8")
    print(f"\nGenerated: {OUTPUT}")


if __name__ == "__main__":
    main()
