"""InferredRule — a Rule generated by the RuleInference engine with metadata."""
from __future__ import annotations

import time
from dataclasses import dataclass, field
from uuid import uuid4

from models.rule import Rule
from models.rule_lifecycle import RuleLifecycle


@dataclass
class InferredRule:
    """A Rule produced by the inference engine, with source context.

    Wraps a standard Rule with inference metadata:
      - source_examples: the (original, desired) pairs used for inference
      - created_at: UNIX timestamp of inference
      - lifecycle: current lifecycle state (defaults to INFERRED)

    The wrapped Rule is a fully valid Rule that can be opened in an
    EditSession, saved as a Preset, or executed directly.
    """

    rule: Rule
    source_examples: list[tuple[str, str]] = field(default_factory=list)
    created_at: float = field(default_factory=time.time)
    lifecycle: RuleLifecycle = RuleLifecycle.INFERRED
    id: str = field(default_factory=lambda: str(uuid4()))

    @property
    def name(self) -> str:
        return self.rule.name

    @property
    def steps(self) -> list:
        return self.rule.steps

    def promote_to(self, state: RuleLifecycle) -> None:
        """Advance lifecycle state (one-way — never demote)."""
        self.lifecycle = state
