"""RuleLifecycle — lifecycle states for Rule objects within the Rule IDE.

The lifecycle tracks a Rule's journey from inference through editing,
testing, to execution.  These are conceptual states — no behavioural
state machine is enforced at the data model level.
"""
from __future__ import annotations

from enum import Enum, auto


class RuleLifecycle(Enum):
    """Rule lifecycle states.

    INFERRED  — generated by RuleInference, not yet reviewed
    EDITABLE  — opened in EditSession, being modified
    TESTED    — validated against test examples
    EXECUTABLE — committed, ready for execution / reuse
    """

    INFERRED = auto()
    EDITABLE = auto()
    TESTED = auto()
    EXECUTABLE = auto()
